### ISSUE TITLE
Create rules for `SimpleEvaluationContext`

### ISSUE THREAD

**Issue by jmle** [konveyor/rulesets#142]
According to the [migration guide](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.0-Release-Notes#core-container):

> SimpleEvaluationContext disables array allocations now, aligned with regular constructor resolution.

Investigate and create rules if necessary.

In the rule description and message, try to be as verbose and clear as possible. Code examples are always welcome and useful. Feel free to use markdown syntax for these.

**Comment by jmle** [comment]
Requires more investigation

**Comment by jayfray12** [comment]
Work complete and PR merged
