### ISSUE TITLE
Rename 'openshift' ruleset directory to 'cloud-readiness'

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/rulesets#6]
Consider renaming https://github.com/konveyor/rulesets/tree/main/default/generated/openshift to 'cloud-readiness'.

Related to https://github.com/windup/windup-rulesets/pull/974

which renamed these rules to:
https://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/cloud-readiness

**Comment by AdiAkhileshSingh15** [comment]
Sir, so this task is mainly about renaming the directory? As altering 'openshift' to 'cloud-readiness' elsewhere might will URLs.
I would like to get this task done.

**Comment by jwmatthews** [comment]
@pranavgaikwad can you help identify what other changes we need to consider for this beyond updating the directory name, I assume there is a mapping we need to update with the Hub and data that is seeded?
