### ISSUE TITLE
EAP7 few RESTEasy rules don't look to find relevant lines

### ISSUE THREAD

**Issue by aufi** [konveyor/rulesets#85]
![image](https://github.com/user-attachments/assets/085b73ac-5ebf-41ee-94c4-47e10da5ff16)

Konveyor version
0.5.0-beta.1

Tested with Konveyor app
Target: eap7
Source: none
Source code used: https://github.com/windup/windup-sample-apps/blob/master/sample-binaries/ticket-monster.war
Rule triggered: resteasy-eap6-000140, resteasy-eap6-000141, resteasy-eap6-000142
File: /shared/bin/java-project/src/main/java/org/jboss/examples/ticketmonster/rest/BaseEntityService.java

**Comment by dymurray** [comment]
opening a separate bug to address annotations with arguments that the rule wants to check.

@jmle to open a bug to track it

**Comment by dymurray** [comment]
https://github.com/konveyor/analyzer-lsp/issues/655
