### ISSUE TITLE
EAP7 SessionBean incident doesn't look relevant

### ISSUE THREAD

**Issue by aufi** [konveyor/rulesets#86]
![image](https://github.com/user-attachments/assets/dd7daed6-1e5f-4c27-bcc2-b0509691abdf)

Konveyor version
0.5.0-beta.1

Tested with Konveyor app
Target: eap7
Source: none
Source code used: https://github.com/windup/windup-sample-apps/blob/master/sample-binaries/ticket-monster.war
Rule triggered: singleton-sessionbean-00001
File: /shared/bin/java-project/src/main/java/org/jboss/examples/ticketmonster/service/BotService.java
Title: Removed SessionBean interface

**Comment by dymurray** [comment]
This rule wasn't converted properly. It's matching too broadly due to the annotation rule wanting to check for arguments inside of the annotation.
